### ISSUE TITLE
关于设备间BLE自动连接问题

### ISSUE THREAD

**Issue by linkjapan** [CANDY-HOUSE/SesameSDK_ESP32_with_DemoApp#3]
现象：
1. Sesame设备与ESP32网关配对成功后，重新启动ESP32网关，设备之间不会自动重连。
2. Sesame设备重置后，重新启动ESP32网关，设备之间可以自动重连。

希望：
一旦配对成功，在不重置的前提下，设备之间可以自动重连。

[20231225_BLE_log_3.txt](https://github.com/CANDY-HOUSE/SesameSDK_ESP32_with_DemoApp/files/13784863/20231225_BLE_log_3.txt)

**Comment by MotoZe** [comment]
尊敬的客戶，

感謝您對我們的GitHub項目提出寶貴的問題。關於您提到的Sesame設備與ESP32網關在重啟後無法自動重連的問題，我們已經進行了詳細的檢查。目前的範例代碼是這樣設計的：當發現附近未註冊的Sesame設備時，系統會自動進行註冊並控制其開關（詳細功能可參見README文件）。

針對您的需求，我們建議在註冊Sesame設備後（參見 ssm_cmd.c 的第35行），將 device_secret 信息儲存至ESP32網關的flash記憶體中。這樣，在網關重啟時，系統可以從flash中讀取 device_secret 並將其寫回 p_ssms_env.ssm.device_secret，從而實現自動重連的功能。當系統在重啟後檢測到已儲存的 device_secret，它將自動執行登入流程，連接至先前註冊的Sesame設備。

希望這個解決方案能夠符合您的需求，如果有任何進一步的疑問或需要協助，歡迎隨時聯繫我們。

**Comment by aoki68k-lj** [comment]
@MotoZe 
I tried saving the DeviceSecret when connecting for the first time, and using that DeviceSecret the next time it starts up.
I was able to reconnect.
thank you very much.
